---
- name: Jenkins Setup
  become: true  
  tasks:
    - name: jenkins apt key
      apt_key:
        url:  https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present
    
    - name: jenkins apt repository
      apt_repository:
        repo: 'deb https://pkg.jenkins.io/debian-stable binary'
        state: present

    - name: install java 
      apt: 
        name: openjdk-21-jre
        state: present

    - name: install jenkins
      apt:
        name: jenkins
        state: present  

    - name: start jenkins service 
      service: 
        name: jenkins 
        state: started 

    - name: enable jenkins to start at boot time 
      service: 
        name: jenkins 
        enabled: yes 