---
- name: install maven
  hosts: jenkins-slave
  become: true  
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: install java
      apt: 
        name: openjdk-21-jre
        state: present

    - name: download mavan package
      get_url:
        url: https://archive.apache.org/dist/maven/maven-3/3.9.4/binaries/apache-maven-3.9.4-bin.tar.gz
        dest: /tmp/apache-maven-3.9.4-bin.tar.gz

    - name: extract maven package
      unarchive:
        src: /tmp/apache-maven-3.9.4-bin.tar.gz
        dest: /opt/apache-maven
        remote_src: yes

    - name: create symbolic link for maven
      file: 
        src: /opt/apache-maven
        dest: /opt/maven
        state: link
    - name: set maven environment variables
      copy:
        dest: /etc/profile.d/maven.sh
        content: |
          export M2_HOME=/opt/maven
          export MAVEN_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}
        mode: '0755'

    - name: load maven environment variables
      shell: source /etc/profile.d/maven.sh
  
    - name: install docker
      apt:
        name: docker.io
        state: present
  
    - name: start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: give 777 permissions on /var/run/docker.sock
      file: 
        path: /var/run/docker.sock
        state: file 
        mode: 0777

    - name: start docker on boot time 
      service: 
        name: docker 
        enabled: yes